In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv(r"C:\Users\Ravikumar L\Downloads\customer_shopping_behavior.csv")

In [5]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [6]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [7]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [8]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [14]:
df.columns=df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")

In [16]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [17]:
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [18]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [20]:
#create a new columns by feature engineering
# create different age groups using qcut 
# qcut is function that divedes column into different labels as defined
labels =["Young adults",'Adult','Middle-aged','Senior']
df['age_group']=pd.qcut(df['age'], q=4, labels = labels)

In [22]:
df[['age','age_group']].head(10)

   age     age_group
0   55   Middle-aged
1   19  Young adults
2   50   Middle-aged
3   21  Young adults
4   45   Middle-aged
5   46   Middle-aged
6   63        Senior
7   27  Young adults
8   26  Young adults
9   57   Middle-aged

In [38]:
# create a column with frequenncy in number form
frequency_mapping = {
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Annually':365,
    'Bi-Weekly':14
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [40]:
df[['frequency_of_purchases','purchase_frequency_days']].head(15)

   frequency_of_purchases  purchase_frequency_days
0             Fortnightly                     14.0
1             Fortnightly                     14.0
2                  Weekly                      7.0
3                  Weekly                      7.0
4                Annually                    365.0
5                  Weekly                      7.0
6               Quarterly                     90.0
7                  Weekly                      7.0
8                Annually                    365.0
9               Quarterly                     90.0
10              Bi-Weekly                     14.0
11            Fortnightly                     14.0
12            Fortnightly                     14.0
13                 Weekly                      7.0
14                 Weekly                      7.0

In [41]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [44]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [48]:
df=df.drop('promo_code_used',axis=1)

In [49]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'frequency_in_numbers',
       'purchase_frequency_days'],
      dtype='object')

In [54]:
df=df.drop('frequency_in_numbers',axis=1)

In [55]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [50]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-win_amd64.whl.metadata (5.1 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.46-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.3.1-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ravikumar l\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.12.2)
Downloading psycopg2_binary-2.9.11-cp312-cp312-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   ----------- ---------------------------- 0.8/2.7 MB 2.1 MB/s eta 0:00:01
   --------------- ------------------------ 1.0/2.7 MB 1.9 MB/s eta 0:00:01
   ----------------------- ---------------- 1.6/2.7 MB 1.9 MB/s eta 0:00:01
   --------------------------- ------------ 1.8/2.7 MB 1.9 MB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.7 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 1.9 MB/s eta 0:00:00
Downloading sqlalchemy-2.0.46-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 1.7 MB/s eta 0:00:01
   ------------------- -------------------- 1.0/2.1 MB 1.6 MB/s eta 0:00:01
   ------------------------ --------------- 1.3/2.1 MB 1.7 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 1.7 MB/s eta 0:00:00
Downloading greenlet-3.3.1-cp312-cp312-win_amd64.whl (227 kB)
Installing collected packages: psycopg2-binary, greenlet, sqlalchemy
Successfully installed greenlet-3.3.1 psycopg2-binary-2.9.11 sqlalchemy-2.0.46
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0
[notice] To update, run: C:\Users\Ravikumar L\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

In [56]:
from sqlalchemy import create_engine

#connect to postgresql
username="postgres"
password="0311"
host="localhost"
port="5432"
database="customer_behavior"

engine=create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#load dataframe into postgresql
table_name="customer"
df.to_sql(table_name,engine,if_exists="replace",index=False)
print(f"Data successfully loaded into table {table_name} in database {database}:")

Data successfully loaded into table customer in database customer_behavior: